CREATE TABLE AUTHOR(
    AUTHOR_ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE BOOK(
    BOOK_ID INT IDENTITY PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CATEGORY_TYPE INT NOT NULL,
    AUTHOR_ID VARCHAR(255) NOT NULL,
    ISBN VARCHAR(255) NOT NULL,
    PUBLISH_DATE DATE NOT NULL,
    AVAILABLE_FROM DATE NOT NULL,

    CONSTRAINT FK_AUTHOR_BOOK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);

CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS INT NOT NULL,
    NO_OF_BOOKS_ISSUED INT NOT NULL
);

CREATE TABLE BOOK_ISSUED(
    BOOK_ISSUED_ID INT IDENTITY PRIMARY KEY,
    BOOK_ID INT NOT NULL,
    MEMBER_ID VARCHAR(255) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    RETURN_DATE DATE NOT NULL,
    STATUS INT NOT NULL,

    CONSTRAINT FK_BOOK_ISSUED_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_BOOK_ISSUED_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);



